[package]
name = "misc_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "RSmiscLib"
crate-type = ["cdylib"]

[dependencies.cpython]
version = "0.7.0"
features = ["extension-module"]
