version: '3'
services:
  app:
    image: space-bot
    build:
      context: .
      dockerfile: Dockerfile
    hostname: Docker Container
    # ports:
      # - 8000:8000
    volumes:
      - .:/app
      # - ./requirements.txt:/app/requirements.txt
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
    command: bash -c "python setup.py && python main.py"
