version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
      # - 8000:8000
    volumes:
      - .:/app
      # - ./requirements.txt:/app/requirements.txt
    environment:
      - PYTHONUNBUFFERED=1
    command: bash -c "python setup.py && python main.py"
